In [83]:
import pandas as pd
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [84]:
pre_savgol_df = pd.read_csv('2024_proj_pre_savgol_filtering.csv')
pre_savgol_df['GP'] = pre_savgol_df['GPprb'] * 82
pre_savgol_df['G/60'] = pre_savgol_df['Gper1kChunk']/1000*2 * 60
pre_savgol_df['A1/60'] = pre_savgol_df['A1per1kChunk']/1000*2 * 60
pre_savgol_df['A2/60'] = pre_savgol_df['A2per1kChunk']/1000*2 * 60
pre_savgol_df['P/60'] = pre_savgol_df['G/60'] + pre_savgol_df['A1/60'] + pre_savgol_df['A2/60']
pre_savgol_df['G'] = pre_savgol_df['G/60']/60 * pre_savgol_df['GP'] * pre_savgol_df['ATOI']
pre_savgol_df['A'] = (pre_savgol_df['A1/60'] + pre_savgol_df['A2/60'])/60 * pre_savgol_df['GP'] * pre_savgol_df['ATOI']
pre_savgol_df['P'] = pre_savgol_df['P/60']/60 * pre_savgol_df['GP'] * pre_savgol_df['ATOI']
pre_savgol_df = pre_savgol_df.sort_values(by='P', ascending=False)
pre_savgol_df = pre_savgol_df.drop(columns=['GPprb', 'Gper1kChunk', 'A1per1kChunk', 'A2per1kChunk'])
pre_savgol_df

,PlayerID,Player,Position,Team,Age,ATOI,GP,G/60,A1/60,A2/60,P/60,G,A,P
124,8476453,Nikita Kucherov,R,TBL,30,21.707329,72.333333,1.495800,2.108457,1.292845,4.897101,39.144170,89.009990,128.154160
26,8477492,Nathan MacKinnon,C,COL,28,22.842560,73.333333,1.635693,1.603621,1.250824,4.490138,45.666398,79.692342,125.358741
276,8478402,Connor McDavid,C,EDM,26,21.359823,68.000000,1.200689,2.263212,1.379857,4.843758,29.066035,88.190685,117.256720
39,8478550,Artemi Panarin,L,NYR,32,20.136546,73.333333,1.782088,1.345658,1.236551,4.364298,43.859569,63.551620,107.411188
44,8477956,David Pastrnak,R,BOS,27,19.957662,73.333333,1.725580,1.431864,0.881147,4.038591,42.091546,56.420583,98.512130
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1063,8480977,Semyon Der-Arguchintsev,C,TOR,23,2.000000,1.000000,0.200510,0.212949,0.167685,0.581144,0.006684,0.012688,0.019371
1078,8477981,Roland McKeown,D,NaN,27,2.000000,1.000000,0.184711,0.178039,0.213646,0.576396,0.006157,0.013056,0.019213
1068,8481649,Joona Luoto,L,NaN,26,2.000000,1.000000,0.217636,0.194216,0.158280,0.570131,0.007255,0.011750,0.019004
1074,8480328,David Gust,R,NaN,29,2.000000,1.000000,0.199702,0.185877,0.156296,0.541875,0.006657,0.011406,0.018062
1065,8478367,Cole Bardreau,C,NaN,30,2.000000,1.000000,0.180407,0.182773,0.149410,0.512590,0.006014,0.011073,0.017086

In [85]:
post_savgol_df = pd.read_csv('2024_proj_post_savgol_filtering.csv')
post_savgol_df['GP'] = post_savgol_df['GPprb'] * 82
post_savgol_df['G/60'] = post_savgol_df['Gper1kChunk']/1000*2 * 60
post_savgol_df['A1/60'] = post_savgol_df['A1per1kChunk']/1000*2 * 60
post_savgol_df['A2/60'] = post_savgol_df['A2per1kChunk']/1000*2 * 60
post_savgol_df['P/60'] = post_savgol_df['G/60'] + post_savgol_df['A1/60'] + post_savgol_df['A2/60']
post_savgol_df['G'] = post_savgol_df['G/60']/60 * post_savgol_df['GP'] * post_savgol_df['ATOI']
post_savgol_df['A'] = (post_savgol_df['A1/60'] + post_savgol_df['A2/60'])/60 * post_savgol_df['GP'] * post_savgol_df['ATOI']
post_savgol_df['P'] = post_savgol_df['P/60']/60 * post_savgol_df['GP'] * post_savgol_df['ATOI']
post_savgol_df = post_savgol_df.sort_values(by='P', ascending=False)
post_savgol_df = post_savgol_df.drop(columns=['GPprb', 'Gper1kChunk', 'A1per1kChunk', 'A2per1kChunk'])
post_savgol_df

,PlayerID,Player,Position,Team,Age,ATOI,GP,G/60,A1/60,A2/60,P/60,G,A,P
1,8476453,Nikita Kucherov,R,TBL,30,21.707329,79.810852,1.690435,2.247079,1.387420,5.324934,48.810748,104.944993,153.755741
3,8477492,Nathan MacKinnon,C,COL,28,22.842560,80.023971,1.832027,1.737848,1.338820,4.908694,55.814296,93.733349,149.547645
0,8478402,Connor McDavid,C,EDM,26,21.359823,78.584345,1.366080,2.402820,1.474905,5.243805,38.217175,108.482431,146.699607
5,8478550,Artemi Panarin,L,NYR,32,20.136546,80.020952,1.980289,1.473900,1.322743,4.776932,53.182177,75.105971,128.288148
23,8477956,David Pastrnak,R,BOS,27,19.957662,80.019441,1.923744,1.562536,0.957243,4.443523,51.203684,67.068155,118.271839
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
877,8484259,Ondrej Pavel,C,NSH,30,6.536225,2.442799,0.171288,0.156757,0.145376,0.473421,0.045582,0.080401,0.125983
591,8476915,Jujhar Khaira,L,NaN,29,2.000000,1.914767,0.622677,0.474956,0.325006,1.422638,0.039743,0.051058,0.090801
851,8478956,Samuel Laberge,L,NJD,26,3.883108,2.398703,0.178745,0.190141,0.157363,0.526248,0.027748,0.053947,0.081695
705,8480274,Philip Kemp,D,NaN,24,4.003123,1.960295,0.182898,0.151815,0.257644,0.592357,0.023921,0.053552,0.077473
872,8483045,Cameron Butler,R,CBJ,30,2.000000,1.844395,0.175411,0.162290,0.147665,0.485366,0.010784,0.019056,0.029840

In [86]:
target_df = pd.read_csv('2023-2024_skater_data.csv')
target_df = target_df[['PlayerID', 'Player', 'Team', 'Position', 'GP', 'TOI', 'Goals', 'First Assists', 'Second Assists', 'Total Points']]
target_df['ATOI'] = target_df['TOI']/target_df['GP']
target_df['G/60'] = target_df['Goals']/target_df['ATOI']/target_df['GP']*60
target_df['A1/60'] = target_df['First Assists']/target_df['ATOI']/target_df['GP']*60
target_df['A2/60'] = target_df['Second Assists']/target_df['ATOI']/target_df['GP']*60
target_df['P/60'] = target_df['Total Points']/target_df['ATOI']/target_df['GP']*60
target_df['G'] = target_df['Goals']
target_df['A'] = target_df['First Assists'] + target_df['Second Assists']
target_df['P'] = target_df['Total Points']
target_df = target_df.sort_values(by='P', ascending=False)
target_df = target_df.drop(columns=['TOI', 'Goals', 'First Assists', 'Second Assists'])
target_df
# target_df

,PlayerID,Player,Team,Position,GP,Total Points,ATOI,G/60,A1/60,A2/60,P/60,G,A,P
59,8476453,Nikita Kucherov,TBL,R,81,144,21.668724,1.504131,2.119457,1.299022,4.922609,44,100,144
40,8477492,Nathan MacKinnon,COL,C,82,140,22.814228,1.635693,1.603621,1.250824,4.490138,51,89,140
66,8478402,Connor McDavid,EDM,C,76,132,21.359211,1.182776,2.291628,1.404546,4.878950,32,100,132
112,8478550,Artemi Panarin,NYR,L,82,120,20.118902,1.782088,1.345658,1.236551,4.364298,49,71,120
121,8477956,David Pastrnak,BOS,R,82,110,19.929675,1.725580,1.431864,0.881147,4.038591,47,63,110
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
747,8474062,Riley Nash,NYR,C,1,0,11.083333,0.000000,0.000000,0.000000,0.000000,0,0,0
724,8481578,Graeme Clarke,NJD,R,3,0,11.383333,0.000000,0.000000,0.000000,0.000000,0,0,0
720,8483489,Fraser Minten,TOR,C,4,0,11.433333,0.000000,0.000000,0.000000,0.000000,0,0,0
718,8483398,Declan Carlile,TBL,D,1,0,11.450000,0.000000,0.000000,0.000000,0.000000,0,0,0
923,8483045,Cameron Butler,CBJ,R,1,0,0.900000,0.000000,0.000000,0.000000,0.000000,0,0,0

In [87]:
results = target_df.copy()
results = results.merge(pre_savgol_df[['PlayerID', 'GP', 'ATOI', 'G/60', 'A1/60', 'A2/60', 'P/60', 'G', 'A', 'P']], on='PlayerID', how='inner', suffixes=('', '_presavgol'))
results = results.merge(post_savgol_df[['PlayerID', 'GP', 'ATOI', 'G/60', 'A1/60', 'A2/60', 'P/60', 'G', 'A', 'P']], on='PlayerID', how='inner', suffixes=('', '_postsavgol'))
results = results[results['GP'] > 50]
results

,PlayerID,Player,Team,Position,GP,Total Points,ATOI,G/60,A1/60,A2/60,...,P_presavgol,GP_postsavgol,ATOI_postsavgol,G/60_postsavgol,A1/60_postsavgol,A2/60_postsavgol,P/60_postsavgol,G_postsavgol,A_postsavgol,P_postsavgol
0,8476453,Nikita Kucherov,TBL,R,81,144,21.668724,1.504131,2.119457,1.299022,...,128.154160,79.810852,21.707329,1.690435,2.247079,1.387420,5.324934,48.810748,104.944993,153.755741
1,8477492,Nathan MacKinnon,COL,C,82,140,22.814228,1.635693,1.603621,1.250824,...,125.358741,80.023971,22.842560,1.832027,1.737848,1.338820,4.908694,55.814296,93.733349,149.547645
2,8478402,Connor McDavid,EDM,C,76,132,21.359211,1.182776,2.291628,1.404546,...,117.256720,78.584345,21.359823,1.366080,2.402820,1.474905,5.243805,38.217175,108.482431,146.699607
3,8478550,Artemi Panarin,NYR,L,82,120,20.118902,1.782088,1.345658,1.236551,...,107.411188,80.020952,20.136546,1.980289,1.473900,1.322743,4.776932,53.182177,75.105971,128.288148
4,8477956,David Pastrnak,BOS,R,82,110,19.929675,1.725580,1.431864,0.881147,...,98.512130,80.019441,19.957662,1.923744,1.562536,0.957243,4.443523,51.203684,67.068155,118.271839
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655,8473446,Erik Johnson,PHI,D,67,6,14.473383,0.309369,0.000000,0.061874,...,6.957987,71.291915,14.422483,0.343253,0.070753,0.115869,0.529875,5.882250,3.198092,9.080342
673,8481122,Simon Benoit,TOR,D,64,5,17.241927,0.054373,0.054373,0.163120,...,5.579525,68.743401,17.238165,0.072732,0.081519,0.190708,0.344960,1.436469,5.376542,6.813011
695,8475235,Nicolas Deslauriers,PHI,L,60,4,8.149444,0.122708,0.122708,0.245416,...,4.723827,65.430112,8.099823,0.258065,0.126764,0.266220,0.651049,2.279458,3.471177,5.750635
706,8477527,Ross Johnston,ANA,L,68,4,8.197059,0.107643,0.107643,0.215285,...,4.301161,70.853388,8.210728,0.131300,0.120496,0.259762,0.511558,1.273078,3.686968,4.960046
711,8477244,Chad Ruhwedel,NYR,D,52,4,12.701282,0.090845,0.090845,0.181690,...,5.108537,56.712997,12.668192,0.107365,0.150801,0.245338,0.503505,1.285613,4.743448,6.029061

In [88]:
# Define the stat columns to compare
stat_columns = [
    "P/60", "ATOI", "G/60", "A1/60", "A2/60", "G", "A", "P", "GP"
]

# Create a dictionary to store MSE results
mse_results = {"Stat": [], "MSE Projections 1": [], "MSE Projections 2": []}

# Compute MSE for each stat
for stat in stat_columns:
    mse1 = mean_squared_error(results[stat], results[f'{stat}_presavgol'])
    mse2 = mean_squared_error(results[stat], results[f'{stat}_postsavgol'])
    
    mse_results["Stat"].append(stat)
    mse_results["MSE Projections 1"].append(mse1)
    mse_results["MSE Projections 2"].append(mse2)

mse_table = pd.DataFrame(mse_results)
mse_table

    Stat  MSE Projections 1  MSE Projections 2
0   P/60           0.006258           0.062947
1   ATOI           0.001390           0.001390
2   G/60           0.001801           0.013375
3  A1/60           0.001448           0.007992
4  A2/60           0.000955           0.003715
5      G           3.800028           8.705162
6      A           9.144407          16.826167
7      P          22.330881          47.195401
8     GP          58.015641          33.199270

In [89]:
# do the same but with MAE
stat_columns = [
    "P/60", "ATOI", "G/60", "A1/60", "A2/60", "G", "A", "P", "GP"
]

# Create a dictionary to store MAE
mae_results = {"Stat": [], "MAE Projections 1": [], "MAE Projections 2": []}

# Compute MAE for each stat
for stat in stat_columns:
    mae1 = mean_absolute_error(results[stat], results[f'{stat}_presavgol'])
    mae2 = mean_absolute_error(results[stat], results[f'{stat}_postsavgol'])
    
    mae_results["Stat"].append(stat)
    mae_results["MAE Projections 1"].append(mae1)
    mae_results["MAE Projections 2"].append(mae2)

mae_table = pd.DataFrame(mae_results)
mae_table

    Stat  MAE Projections 1  MAE Projections 2
0   P/60           0.041365           0.228816
1   ATOI           0.030347           0.030347
2   G/60           0.021068           0.098522
3  A1/60           0.020622           0.080461
4  A2/60           0.015793           0.055469
5      G           1.491415           2.451808
6      A           2.438282           3.594222
7      P           3.842499           6.020564
8     GP           7.240098           4.174471